### PR TITLE
Some ideas

### LINKED ISSUE #1: Some ideas
Hi,

Because your idea is brilliant, THANK YOU :kissing_heart:

But it's a bit annoying that the plugin (through its only filter `acf_svg_icon_filepath`) doesn't allow us to specify an SVG file for a particular ACF field (by `{$field_key}` or `{$field_name}`) :confused: 
I don't know if it was a technical restriction or a personal choice (no need at first) but IMHO it could be very useful to be able to do it :blush:

Second point a bit more specific :wink: It could be very useful to be able to change/translate the texts associated to the SVG icons. Most of the time, the SVG id names are a personal fight for the developper :unamused: and don't represent exactly what they are. Because clients can manage/choose their icons in some cases, it's really important to give them a beautiful transcript.

For the fun, it could be interesting to improve the way the icons are used into Select2. Instead of using a symbol from in-document sprite, we could use the symbol directly from the external sprite (e.g.: `<use xlink:href="/path/to/icons.svg#newspaper"></use>`) :simple_smile:

If you continue to use this plugin and are interested in these changes, I will be happy to submit a PR :bowtie:

Best regards,
Xavier.

### PR DESCRIPTION
**Pull request by 7studio**
Hi @MaximeCulea,

I hope the WCEU was interesting :wink: 

I tried to slice my PR into little commits to allow you to pick up some of them if you don't want particular changes. Do not hesitate to give me your feedbacks. It's always interesting to improve my skills and my understanding of PHP or WP (I'm not a back-end dev) :blush:

We could go further in the process of the plugin: ajax loading, disabled options, etc. But IMO that is not bad as it is.

The only thing that I wonder about is the use of `wp_get_cache` instead of `get_transient` but maybe it doesn't matter.

Fixes #1.

Have a good day,
Xavier.

### CODE REVIEW

**Comment by MaximeCulea** [comment]
Hello @7studio, we will have a look soon.
Thx for your help.

**Comment by Rahe** [comment]
IS it possible to make a pull request only with the modifications ? here you make a pull request with big files changes but there is no modifications on these files really, maybe mod changed ?

**Comment by 7studio** [comment]
Hi @Rahe,

I'm a bit disappointed because the code is totally different from the beginning :unamused:

You are right, the default diff of GitHub is difficult to read/understand but my pull request contains 12 commits and it would be more interesting to check the changes commit by commit.

The main big files changes are due to the commits 6610a86 and 22feea6. I don't know what I can do to help your review sorry :pensive:

**Comment by Rahe** [comment]
Hi, we will review your commits for the project. Maybe we will not take as is and integrate only thé changes.
Thank you again for your time :)

**Comment by MaximeCulea** [comment]
It's on process : https://github.com/BeAPI/acf-svg-icon/tree/pr-2

**Comment by 7studio** [comment]
Hi @MaximeCulea 

Thank you for taking into account my work :blush: From the beginning, I'm confused and I don't understand why you don't merge all these changes via my PR instead of rewriting your own commits. I'm really interested in knowing your opinion about my process/work in this PR and this lack of understanding for my new/next contributions :wink:

**Comment by Rahe** [comment]
Hello,

We are reviewing all the code and checking if everything is okay. 
We aren't agree with every changes you've made and we want to be sure that all your changes matches with our coding standards.
For example remaking all our package.json isn't productive and not necessary or prefixing our constants with `BEA_` will break backcompatibility.

We prefer to focus on adding the feature than change everything. Here maybe (we do not have reviewed everything) some code parts have to be rewrited.
We want to add this feature but with other changes like the ability to load multiple SVG files at once.

**Comment by 7studio** [comment]
Thank you for your answer Nicolas. I understand your point of view and I agree with you :blush: 

However, I don't totally agree with your idea about the `package.json` but it's your plugin. I tried to improve it because it was there but IMO it could be removed. Concerning the constants and the `BEA_` prefix, it's your own conventions: https://github.com/BeAPI/bea-plugin-boilerplate/blob/master/bea-plugin-boilerplate.php#L42-L47 and IMHO it doesn't introduce any break for backcompatibility :relieved: except if you have used these contants outside the plugin…

**Pull request closed without merging**
